feat: added file the way remix wants it
ApeWorX/hosted-compiler pull request #24
Opened 2023-11-03 15:58 UTC by Ninjagod1251

We are going to accept a manifest format and return the same format with the compiled artifact.

This will help remix not have to convert and return files. It makes it simpler for both parties around

2023-11-06 19:40 UTC, sabotagebeats commented
How can I test this for you @Ninjagod1251

2023-11-06 19:41 UTC, sabotagebeats requested changes
How can I test this for you?

2023-11-11 00:05 UTC, fubuloubu commented on main.py
>      tasks[project_root.name] = TaskStatus.SUCCESS
```suggestion
         try:
             results[project_root.name] = project.extract_manifest()
             tasks[project_root.name] = TaskStatus.SUCCESS
         except Exception as e:
             results[project_root.name] = [str(e)]
             tasks[project_root.name] = TaskStatus.FAILED
```

2023-11-13 15:08 UTC, antazoey commented
> How can I test this for you?

Testing instructions:

1. Launch app via `uvicorn main:app --reload`
2. Navigate to http://127.0.0.1:8000/docs in your browser
3. Click on the `compile` tab
4. It should pop open a little example and stuff

Previously without this PR, it would show a frozen loading circle and your browser would basically crash. LOL.
It is some bug in a Swagger Javascript U thing and has nothing to do with anything in Ape or even FastAPI. It is an OpenAPI (swagger) bug...

And thus our workaround here is to force the UI to load from an older version, at least that is what I think is happening... I kinda am just jumping in and helping, Chris if you have time, accurately explain what this workaround is doing.

> I add the workaround, can you test to see if you can reproduce the bug anymore? I can't reproduce it anymore

It works now! This is so cool, I am glad you got it working, thank you.

2023-11-13 15:08 UTC, antazoey approved these changes
nice work!

2023-11-13 18:36 UTC, fubuloubu approved these changes
It might be handy to pull out the bug fixes on another PR, I don't think the EF folks have had time to review this

2023-11-13 18:36 UTC, fubuloubu commented on main.py
> +    return results[task_id]
These changes are important bug fixes

2023-11-13 18:36 UTC, fubuloubu commented on main.py
> +             tasks[project_root.name] = TaskStatus.FAILED
These changes are important bug fixes

2023-11-17 07:15 UTC, fubuloubu approved these changes

2023-11-17 07:16 UTC, merged